export const ADD_EXPENSE = 'ADD_EXPENSE';
export const GET_EXPENSES = 'GET_EXPENSES';
export const GET_EXPENSE = 'GET_EXPENSE';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';
export const GET_TOTAL_BY_CATEGORY = "GET_TOTAL_BY_CATEGORY"
